dubbo:
  consumer:
    check: false
  application:
  #dubbo服务名
    name: sso-web
  protocol:
  #dubbo的RPC协议
    name: consumer
  #dubbo的RPC端口
    port: 20880
  provider:
  #远程服务超时时间
    timeout: 5000
  registry:
  #注册中中心
    address: zookeeper://39.107.253.236:2181
    check: false
  scan:
    base-packages: com.example.sso.controller


